import { describe, it, expect } from 'vitest';
import { CLASS_NAMES, classIndexToLabel } from '../tile-classes';

// This exact order is generated by (private repo) synthetic/tiles.py::CLASS_NAMES
// and is baked into the exported model's output channel order. Any drift here
// silently mislabels every detection, so it's pinned as a literal, not derived.
const EXPECTED = [
  '1m', '2m', '3m', '4m', '5m', '6m', '7m', '8m', '9m',
  '1p', '2p', '3p', '4p', '5p', '6p', '7p', '8p', '9p',
  '1s', '2s', '3s', '4s', '5s', '6s', '7s', '8s', '9s',
  '1z', '2z', '3z', '4z', '5z', '6z', '7z',
  '5mr', '5pr', '5sr',
];

describe('CLASS_NAMES', () => {
  it('matches the training pipeline class order exactly', () => {
    expect(CLASS_NAMES).toEqual(EXPECTED);
  });

  it('has 37 classes', () => {
    expect(CLASS_NAMES).toHaveLength(37);
  });
});

describe('classIndexToLabel', () => {
  it('resolves valid indices', () => {
    expect(classIndexToLabel(0)).toBe('1m');
    expect(classIndexToLabel(36)).toBe('5sr');
  });

  it('throws on out-of-range indices', () => {
    expect(() => classIndexToLabel(-1)).toThrow(/out of range/);
    expect(() => classIndexToLabel(37)).toThrow(/out of range/);
  });
});
